# Generated by Django 6.0.1 on 2026-01-28 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocationStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('land_type', models.CharField(max_length=100)),
                ('avg_temp', models.FloatField()),
                ('avg_rainfall', models.FloatField()),
            ],
        ),
    ]
