# Generated by Django 6.0.3 on 2026-04-11 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recommendationlog',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveField(
            model_name='recommendationlog',
            name='district',
        ),
        migrations.AddField(
            model_name='recommendationlog',
            name='humidity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recommendationlog',
            name='irrigation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='recommendationlog',
            name='nitrogen',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recommendationlog',
            name='ph',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recommendationlog',
            name='phosphorus',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recommendationlog',
            name='potassium',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recommendationlog',
            name='rainfall',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recommendationlog',
            name='soil_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='recommendationlog',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recommendationlog',
            name='zone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='recommendationlog',
            name='season',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
