# Generated by Django 6.0.1 on 2026-01-28 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name_en', models.CharField(max_length=100)),
                ('crop_name_np', models.CharField(blank=True, max_length=100)),
                ('season', models.CharField(max_length=100)),
                ('water_requirement', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image_path', models.ImageField(blank=True, null=True, upload_to='crops/')),
            ],
        ),
        migrations.CreateModel(
            name='CropGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soil_preparation', models.TextField()),
                ('sowing_method', models.TextField()),
                ('disease_info', models.TextField()),
                ('harvest_time', models.CharField(max_length=100)),
                ('crop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guides', to='crops.crop')),
            ],
        ),
    ]
