# Generated by Django 6.0.3 on 2026-03-07 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='reminder_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
