# Generated by Django 6.0.3 on 2026-03-07 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_activity_reminder_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='notified',
            field=models.BooleanField(default=False),
        ),
    ]
