# Generated by Django 6.0.3 on 2026-04-30 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_activity_notified'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
